import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from "../components/Header"
import { GetStaticProps } from 'next'


type CountryProps = {
  population: number
  region: string
  name: string
  flags: { svg: string }
  capital: string
}[]

export default function Home({ countries }: { countries: CountryProps }) {
  const handleSearch = (e: React.FormEvent<HTMLInputElement>) => {
    setInputValue(e.currentTarget.value)
    setCountriesData((data) => data.filter((country) => country.name.toLowerCase().includes(inputValue.toLowerCase())))
  }
  const [countriesData, setCountriesData] = useState(countries)
  const [inputValue, setInputValue] = useState("")
  
  const handleFilter = (e: React.ChangeEvent<HTMLSelectElement>) => {

    setCountriesData((data) => data.filter((country) => country.region === e.target.value))
    if (e.target.value === '') return setCountriesData(countries)

  }
  useEffect(()=>{
    if (inputValue.length === 0) {
      setCountriesData(countries)
    }
   
  },[inputValue,countries])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className='flex-input'>
        <input type="text" value={inputValue} onChange={handleSearch} placeholder="search for a country" />
        <select name="filtercountry" id="" onChange={handleFilter}>
          <option value="">Filter by Region</option>
          <option value="Africa">Africa</option>
          <option value="America">America</option>
          <option value="Asia">Asia</option>
          <option value="Europe">Europe</option>
          <option value="Oceania">Oceania</option>
        </select>
      </div>
      <ul>
        {countriesData.map((country) => (
          <Link key={country.name} href={`/${encodeURIComponent(country.name)}`}>
            <Image src={country.flags.svg} alt="flag" width={100} height={100} />
            <p>{country.name}</p>
            <p>{country.population}</p>
            <p>{country.region}</p>
            <p>{country.capital}</p>
          </Link>
        ))}
      </ul>
    </>
  )
}
export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch('https://restcountries.com/v2/all')
  const countries: CountryProps[] = await res.json()
  return {
    props: {
      countries,
    },
  }

}