import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from "../components/Header"
import { GetStaticProps, NextPage } from 'next'

const inter = Inter({ subsets: ['latin'] })
type CountryProps= {
    population: number
    region: string
    name: {common: string}
    flags:{svg: string}
    capital:string[]
  }[]

export default function Home({ countries }:{countries: CountryProps}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
      <div className='flex-input'>
        <input type="text" placeholder="search for a country" />
        <select name="filtercountry" id="">
          <option value="">Filter by Region</option>
          <option value="Africa">Africa</option>
          <option value="America">America</option>
          <option value="Asia">Asia</option>
          <option value="Europe">Europe</option>
          <option value="Oceania">Oceania</option>
        </select>
      </div>
      
      <ul>
        {countries.map((country) => (
          <Link key={country.name.common} href={`/${encodeURIComponent(country.name.common)}`}>
              <Image src={country.flags.svg} alt="flag" width={100} height={100} />
              <p>{country.name.common}</p>
              <p>{country.population}</p>
              <p>{country.region}</p>
              <p>{country.capital}</p>
            </Link>
          ))}
      </ul>
    </>
  )
}
export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch('https://restcountries.com/v3.1/all')
  const countries:CountryProps[] = await res.json()
  return {
    props: {
      countries,
    },
  }

}